### ISSUE TITLE
Unity ViewController hiding Player ViewController

### ISSUE THREAD

**Issue by dwxw** [Thirdpresence-Open/thirdpresence-ad-sdk-ios#1]
I've found a problem playing an ad in a Unity game of ours.  When I go to display the ad, the display method of TRPVideoInterstitial is correctly adding the playerViewController and the ad begins to play.  But after TRPPlayerViewController viewDidAppear: returns, our game viewController returns and 'hides' the ad.

I don't fully understand why this happens, and so far it's only one game, other Unity examples work as expected.  I did play with this [line](https://github.com/Thirdpresence-Open/thirdpresence-ad-sdk-ios/blob/master/ThirdpresenceAdSDK/TPRVideoInterstitial.m#L105) and if you change UIModalPresentationOverFullScreen to UIModalPresentationFullScreen the ad plays fine, and returns to the Unity viewController once it's finished.  The documentation suggests that would occur if the presented view controller wasn't opaque.

Have you got any thoughts on this?  Would switching to UIModalPresentationFullScreen be better?

**Comment by Thirdpresence-Open** [comment]
Thanks for reporting the issue and giving comprehensive details. We will investigate and get back as soon as possible.

**Comment by Thirdpresence-Open** [comment]
It sounds like the problematic game somehow forces the game view controller to be the foremost one. According to Apple documentation the difference with UIModalPresentationFullScreen compared to UIModalPresentationOverFullScreen is that it removes views that are left behind of the presented view controller (TPRPlayerViewController) from the view hierarchy. UIModalPresentationOverFullScreen is used when the presented view controller does not fill the screen with opaque content and the views behind should be show through. Currently we do not have any use cases where the interstitial ad wouldn't fill whole screen. Therefore it should be safe to switch to UIModalPresentationFullScreen. We have run tests and no regression found due this change. We will publish a new version tomorrow, which includes the change.

**Comment by Thirdpresence-Open** [comment]
New SDK version has been published. Closing this issue.

**Comment by dwxw** [comment]
Great, thanks.
